version: "3.2"
services:
  web:
    image: chatroom-apis
    container_name: chatroom-apis
    build: .
    ports:
      - "3000:3000"
  swagger:
    image: swaggerapi/swagger-ui
    container_name: chatroom-apis-swagger
    ports:
      - "3005:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - type: bind
        source: ./api/dist
        target: /swagger
